title: BYOP
description: Bring Your Own Paper Reading Group
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
title-img: https://www.washingtonian.com/wp-content/uploads/2021/06/iStock-1093281524-2048x1365.jpg 
